import path from "node:path";
import fs from "node:fs";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import fse from "fs-extra";
import prompts from "prompts";
import kleur from "kleur";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.join(__dirname, "..", "templates", "default");
const VERSION = "0.2.0";

function banner() {
  console.log();
  console.log(kleur.bold().cyan("  create-secure-stack"));
  console.log(kleur.dim("  Full-stack scaffolding — with auth, RBAC, encryption, and audit logging already wired in.\n"));
}

function printHelp() {
  console.log(`
${kleur.bold().cyan("create-secure-stack")} v${VERSION}

${kleur.bold("Usage:")}
  npx create-secure-stack [project-name] [options]

${kleur.bold("Options:")}
  --help      Show this help message
  --version   Show version number

${kleur.bold("Example:")}
  npx create-secure-stack my-app
`);
}

export async function run(argv) {
  const hasHelp = argv.includes("--help") || argv.includes("-h");
  const hasVersion = argv.includes("--version") || argv.includes("-v");

  if (hasVersion) { console.log(`create-secure-stack v${VERSION}`); return; }
  if (hasHelp) { printHelp(); return; }

  banner();

  const cliArgName = argv.find((a) => !a.startsWith("-"));

  const answers = await prompts(
    [
      {
        type: cliArgName ? null : "text",
        name: "projectName",
        message: "Project name",
        initial: "my-secure-app",
      },
      {
        type: "select",
        name: "database",
        message: "Database",
        choices: [
          { title: "SQLite (fastest — zero setup, try it in 60 seconds)", value: "sqlite" },
          { title: "PostgreSQL (production-ready — requires a running Postgres instance)", value: "postgresql" },
        ],
        initial: 0,
      },
      {
        type: "confirm",
        name: "installDeps",
        message: "Install dependencies now? (backend + frontend)",
        initial: true,
      },
    ],
    {
      onCancel: () => {
        console.log(kleur.red("\nCancelled."));
        process.exit(1);
      },
    }
  );

  const projectName = cliArgName || answers.projectName;
  const targetDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(targetDir) && fs.readdirSync(targetDir).length > 0) {
    console.log(kleur.red(`\n✖ Directory "${projectName}" already exists and is not empty.`));
    process.exit(1);
  }

  console.log(kleur.dim(`\nScaffolding into ./${projectName} ...`));
  await fse.copy(TEMPLATE_DIR, targetDir);

  // --- Configure database provider in the Prisma schema ---
  // The template defaults to sqlite; swap to postgresql when chosen.
  if (answers.database === "postgresql") {
    const schemaPath = path.join(targetDir, "backend", "prisma", "schema.prisma");
    let schema = await fse.readFile(schemaPath, "utf8");
    schema = schema.replace('provider = "sqlite"', 'provider = "postgresql"');
    await fse.writeFile(schemaPath, schema);
  }

  // --- Generate real secrets, never ship placeholder secrets ---
  const jwtSecret = crypto.randomBytes(48).toString("hex");
  const encryptionKey = crypto.randomBytes(32).toString("hex"); // 256-bit key for AES-256-GCM

  const dbUrl =
    answers.database === "sqlite"
      ? "file:./dev.db"
      : "postgresql://postgres:postgres@localhost:5432/" + projectName.replace(/[^a-z0-9_]/gi, "_");

  const envContent = [
    `# Auto-generated by create-secure-stack — keep this file out of version control.`,
    `DATABASE_URL="${dbUrl}"`,
    `JWT_SECRET="${jwtSecret}"`,
    `FIELD_ENCRYPTION_KEY="${encryptionKey}"`,
    `PORT=4000`,
    ``,
    `# URL of your frontend — used for CORS and Origin header validation.`,
    `# In production, update this to your deployed frontend URL.`,
    `FRONTEND_URL="http://localhost:5173"`,
    ``,
    `# Set to "production" in deployed environments to enable the Secure cookie flag.`,
    `NODE_ENV=development`,
    ``,
  ].join("\n");

  await fse.writeFile(path.join(targetDir, "backend", ".env"), envContent);

  // --- Stamp the project name into package.json files ---
  for (const sub of ["backend", "frontend"]) {
    const pkgPath = path.join(targetDir, sub, "package.json");
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(await fse.readFile(pkgPath, "utf8"));
      pkg.name = `${projectName}-${sub}`;
      await fse.writeFile(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
    }
  }

  console.log(kleur.green(`✔ Project created at ./${projectName}`));
  console.log(kleur.dim(`  Database: ${answers.database}`));
  console.log(kleur.dim(`  A fresh JWT secret and field-encryption key were generated into backend/.env\n`));

  if (answers.installDeps) {
    const { execSync } = await import("node:child_process");
    console.log(kleur.dim("Installing backend dependencies..."));
    execSync("npm install", { cwd: path.join(targetDir, "backend"), stdio: "inherit" });
    console.log(kleur.dim("Installing frontend dependencies..."));
    execSync("npm install", { cwd: path.join(targetDir, "frontend"), stdio: "inherit" });
  }

  console.log(kleur.bold("\nNext steps:"));
  console.log(kleur.cyan(`  cd ${projectName}/backend`));
  if (!answers.installDeps) console.log(kleur.cyan(`  npm install`));
  console.log(kleur.cyan(`  npx prisma migrate dev --name init`));
  console.log(kleur.cyan(`  npm run dev`));
  console.log(kleur.dim(`  # backend runs on http://localhost:4000`));
  console.log();
  console.log(kleur.cyan(`  cd ${projectName}/frontend`));
  if (!answers.installDeps) console.log(kleur.cyan(`  npm install`));
  console.log(kleur.cyan(`  npm run dev`));
  console.log(kleur.dim(`  # frontend runs on http://localhost:5173\n`));
}
